# Configuration file for GitHub Pages

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed

# Site settings
title: KodeKloud CKS Challenge
description: The challenge series test the skills and understanding of Kubernetes security concepts. The challenges in this series cover a broad range of Kubernetes security topics, including network policies, RBAC, seccomp, AppArmor, and others. 
url: https://krishanthisera.github.io/
baseurl: /CKS-Challenges/

# GitHub Pages settings
repository: krishanthisera/CKS-Challenges
